import { Inter } from "next/font/google";
import "./globals.css";
import { NewTaskProvider } from "./context/newTaskContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NewTaskProvider>
      <body className={inter.className}>{children}</body>
      </NewTaskProvider>
    </html>
  );
}
